/**
 * routes/mood/index.ts
 *
 * All mood & wellness routes.
 * Every route here requires a valid JWT (authenticate middleware).
 *
 * Base path: /api/v1/mood
 *
 * Endpoints:
 *   POST /log              → Log mood + get sentiment analysis + recommendations
 *   GET  /history           → Mood history for charts (last N days)
 *   GET  /recommendations   → Latest mood-driven meal/workout recommendations
 */

import { Router } from 'express';
import { authenticate }  from '../../middleware/auth.middleware';
import { validateBody }  from '../../middleware/validate.middleware';
import { moodController } from '../../controllers/mood.controller';
import { logMoodSchema }  from '../../validators/mood.validator';

const router = Router();

// ALL mood routes require a valid JWT
router.use(authenticate);

// ─────────────────────────────────────────────────────────────────────────────
// MOOD LOGGING + ANALYSIS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * POST /api/v1/mood/log
 *
 * Log how a student is feeling. Optionally include a journal entry
 * for sentiment analysis. Returns mood-aware meal and workout plans.
 *
 * Body:
 * {
 *   "mood_score": 4,
 *   "mood_tags": ["stressed", "tired"],
 *   "journal_entry": "Had a rough day, exam pressure...",
 *   "circle_id": "optional-uuid"
 * }
 *
 * Response:
 *   - mood_log: saved database record
 *   - sentiment_analysis: score, label, emotions, primary_emotion
 *   - mood_state: classified state (stressed_anxious, fatigued_low, etc.)
 *   - recommendations.meals: mood-aware meal plan
 *   - recommendations.workout: mood-aware workout plan
 */
router.post(
  '/log',
  validateBody(logMoodSchema),
  moodController.logMood,
);

// ─────────────────────────────────────────────────────────────────────────────
// MOOD HISTORY
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/v1/mood/history?days=30
 *
 * Returns all mood logs for the past N days (default 30, max 90).
 * Includes sentiment scores and primary emotions for trend charts.
 */
router.get('/history', moodController.getMoodHistory);

// ─────────────────────────────────────────────────────────────────────────────
// MOOD-DRIVEN RECOMMENDATIONS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/v1/mood/recommendations
 *
 * Returns the latest mood-aware meal + workout recommendations
 * that haven't expired yet. Generated by POST /log.
 */
router.get('/recommendations', moodController.getRecommendations);

export default router;